### ISSUE TITLE
unexpected keyword argument 'verbose'

### ISSUE THREAD

**Issue by arthur-liqian** [FrancescAlted/ipython_memwatcher#3]
Python 3.7 remove the 'verbose' argument from method namedtuple. _ipython_memwatcher_ raises an _TypeError_ with Python 3.7. 

         34             'Measurements',
         35             ['memory_delta', 'time_delta', 'memory_peak', 'memory_usage'],
    ---> 36             verbose=False)
         37
         38     @property

    TypeError: namedtuple() got an unexpected keyword argument 'verbose'

**Comment by FrancescAlted** [comment]
A fix for this is in the latest release.
